# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(choices=[('default', 'default'), ('elyse', 'elyse'), ('kristy', 'kristy'), ('lena', 'lena'), ('mark', 'mark'), ('matthew', 'matthew'), ('molly', 'molly'), ('rachel', 'rachel')], default='default', max_length=50, verbose_name='Avatar'),
        ),
    ]
